x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: airflow/Dockerfile

  env_file:
    - .env.docker

  environment:
    PYTHONPATH: /opt/airflow/project/src

  depends_on:
    - postgres

services:
  postgres:
    container_name: coffee_postgres
    image: postgres:15

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: coffee_data_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    container_name: coffee_etl

    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env.docker

    stdin_open: true
    tty: true

  airflow-init:
    <<: *airflow-common

    container_name: coffee_airflow_init

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username airflow
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com
      --password airflow
      "
      
  airflow-webserver:
    <<: *airflow-common

    container_name: coffee_airflow_webserver

    command: webserver

    ports:
      - "8080:8080"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project
      - ./.dbt:/home/airflow/.dbt

    restart: unless-stopped

  airflow-scheduler:
    <<: *airflow-common

    container_name: coffee_airflow_scheduler

    command: scheduler

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project
      - ./.dbt:/home/airflow/.dbt

    restart: unless-stopped

  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    container_name: coffee_dbt
    working_dir: /app
    volumes:
      - ./dbt:/app
      - ./.dbt:/root/.dbt
    depends_on:
      - postgres

volumes:
  postgres_data: