x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: airflow/Dockerfile

  env_file:
    - .env.docker

  depends_on:
    - postgres

services:
  postgres:
    container_name: coffee_postgres
    image: postgres:15

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: coffee_data_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    container_name: coffee_etl

    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env.docker

    stdin_open: true
    tty: true

  airflow-init:
    <<: *airflow-common

    container_name: coffee_airflow_init

    command: version

volumes:
  postgres_data: